### PR TITLE
new custom extensions + iter

### PR DESCRIPTION
**Pull request by michael72**
A few other additions as mentioned before 😉 
- better support for iterators: `iter` creates a inline iterator as a result of the command chain
- support for own extensions: see test.nim for detailed examples of that
- small renamings done and functions/elements made public to be used when creating own extensions
- automatic call of `addElem` when the last function is generates a new collection
- enhancements with iterators - counting / using the internal index
I hope creating an extension - well maybe is not piece of cake - but it should be feasible now for any user

### CODE REVIEW

**Comment by alehander42** [comment]
Well, that's amazing: supporting user extensions was something I wanted, but always wondered how hard would it be for the user.

Still, I think we can improve that: the register process seems verbose to me, can't we require convention (always name your custom handlers `inlineX`) and just have

```nim
registerZero inlineX, inlineY
```

and autogenerate the custom handlers command?

Also, having support to directly write your own handler is brilliant, still I hoped to find a way to somehow simplify it in some cases: something like

```nim
zero filter(test: proc(f: T): bool):
  last:
    if adapt(`test`):
      inlineAddElem(`element`)
  default:
    if adapt(`test`):
      nil
```

However the last thing seems impossible in general, so I think your mechanism is better indeed

**Comment by michael72** [comment]
Hi @alehander42 

just a short note - with the registerZero I think is a good idea - but not sure if it's possible like that. It was really hard getting the extensions running without the nim compiler crashing with SIGSEGV or some other interesting error messages ;)

I probably will try to save the extensions in a `set` or `seq` (if that is possible at compile time and without strange crashes) - another possibility would be to generate the delegate function that I programmed manually in the `test.nim` file.

Your DSL looks good, but I don't think that's possible either - maybe in the future? Btw I have removed the `inlineAddElem` - now `addElem` - mostly - from the inline functions. `addElem` does not need to be done explicitly any more in case the `prevIter` is added as a result. That is now done automatically if the current function is the last and registered to `SEQ_HANDLERS` (and `addElem` was not called already) - makes it easier for the user to extend.

Regards
 Michael

**Comment by michael72** [comment]
Hi @alehander42 ,

I did the second solution I suggested - auto generating the extension-delegate function (the one with the case/of inline... calls). It is generated now from an enum, which in turn defines what commands shall be supported.
I could not get just anything working with adding the inline-functions manually (that is what I tried first). An the one with the enum was also tricky. But I think this is not too much overhead.

Oh - great - just seeing, that the travis build failed...
I checked out the project again on this branch, compiled - everything is fine. Maybe a new nim bug??
Could you also check it?
Thanks!

**Comment by alehander42** [comment]
Great, it seems correct!

**Pull request merged**
